### ISSUE TITLE
ATF doesn't compile on ARMv7 but on AARCH64

### ISSUE THREAD

**Issue by umiddelb** [longsleep/build-pine64-image#1]
I'm getting assertion errors, when I try to compile ATF on ARMv7 directly (no-crosscompile), but on AARCH64 ATF builds fine (no cross-compile as well).

The u-boot made out of this ATF (compiled on AARCH64) boots up nicely ;)

**Comment by longsleep** [comment]
Do you think that this ATF should compile on and for armhf? I guess that is not really in the scope of that project. I did not look at the ATF very much but i think it is for arm64 only?

**Comment by umiddelb** [comment]
I assumed I had to build it on armhf, according to your hints mentioned [here](https://github.com/longsleep/build-pine64-image/blob/master/u-boot-postprocess/README.md)

**Comment by longsleep** [comment]
Oh good catch, i guess the ATF part at the beginning is just wrong and a left over from early experiments. In fact the ATF is compiled with the aarch64 toolchain and thus 64bit. I will update that in the docs asap.

**Comment by umiddelb** [comment]
OK, by the way I still experience poor network performance on eth0 even after updating kernel, dtb and u-boot

**Comment by longsleep** [comment]
Docs were updated in https://github.com/longsleep/build-pine64-image/commit/3bfa7103dabde310ccc7e2a7ada82d832776ef8c

**Comment by longsleep** [comment]
@umiddelb i guess the network performance fix will have to wait for the new BSP to finish downloading. It works at 94Mbps for me when connected to a 100M switch. 1000M switch gives only 20-30Mbps probably related to that crude hack i made to force 1000M to 100M.
