### ISSUE TITLE
dtb not generated in 

### ISSUE THREAD

**Issue by nickbetteridge** [longsleep/build-pine64-image#15]
I just built both `https://github.com/apritzel/linux.git linux-a64-v1` and `https://github.com/apritzel/linux.git linux-a64-v4` using 

```
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- clean
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j4 Image
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j4 modules
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j4 dtbs
```

and the files found in both ``arch/arm64/boot/dts/allwinner` trees were :

```
a64.dtsi  Makefile  pine64_common.dtsi  pine64.dts  pine64_plus.dts
```
- is there an extra step required to generate the .dtb file?

Cheers
Nick

**Comment by apritzel** [comment]
Did you do make defconfig before, so that the Allwinner support actually got enabled?

**Comment by longsleep** [comment]
Updated instructions in 1497fde8007d082c81bc36a4552e2141a636088f
