### ISSUE TITLE
change make_rootfs.sh to support centos

### ISSUE THREAD

**Issue by vanloswang** [longsleep/build-pine64-image#19]
Now there is a commity support CentOS aarch edition, Could we changde make_rootfs.sh to support it?

**Comment by umiddelb** [comment]
Do you miss something [here](https://github.com/umiddelb/z2d/tree/master/pine64#centos)?

**Comment by vanloswang** [comment]
@umiddelb Thanks. I could not download your rootfs in my country, the dns to resolve www.dropbox.com is missing. So I could not download it by some free vpn. I try your method with the original CentOS-aarch64.img.xz. I also follow your scripts to complete the changes. But my pine64+ could not boot successfully. I have no tools to monitor the uart output now. The only one interface I can use is the hdmi. Could you share your rootfs to me by email?

**Comment by vanloswang** [comment]
@umiddelb The setups in https://github.com/vanloswang/z2d/tree/master/pine64 maybe out of date. I found out that it is not the same with the steps in your scripts.

**Comment by vanloswang** [comment]
@umiddelb The setups in https://github.com/vanloswang/z2d/tree/master/pine64 maybe out of date. I found out that it is not the same with the steps in your scripts.

**Comment by longsleep** [comment]
Feel free to for the script and add CentOS to it. If you are going to maintain this and also add packaging including a repository then create a PR and i am willing to merge.

**Comment by umiddelb** [comment]
@vanloswang , the [difference](https://github.com/vanloswang/z2d/compare/master...umiddelb:master) you've mentioned is related to the readme only. The file is way too large (380 MB) to send it via email. I've uploaded [the archive](https://dumontsystems-my.sharepoint.com/personal/ulrich_middelberg_dumontsystems_onmicrosoft_com/_layouts/15/guestaccess.aspx?guestaccesstoken=sBzlXTX7OmhV4MZda6pSHYmDfy84437pGiJo%2bXNQ2Mc%3d&docid=1ef88a07989854779ac294cb72738d08c) to my Office365 Account. If this turns out to be inaccessible as well, you might suggest a service to which I can upload to.

**Comment by vanloswang** [comment]
@umiddelb Thank you very much. I am downloading it now.
@longsleep I will try it out.

**Comment by vanloswang** [comment]
@umiddelb @longsleep 
The cmds bellow will make a bootable centos 7.2 sd card. After execute the following cmds, need to update kernel and uboot by using longsleep's platform scripts at this git repo. Later I will test the follow cmds and push it here.

curl http://mirror.centos.org/altarch/7/isos/aarch64/CentOS-aarch64.img.xz -f --progress-bar --output CentOS-aarch64.img.xz
xz -d CentOS-aarch64.img.xz
dd if=CentOS-aarch64.img of=/dev/sdb bs=1M oflag=sync
mount /dev/sdb2 rootfs/
cp -ar rootfs centos7-rootfs
umount rootfs/
dd if=simpleimage-pine64-latest.img of=/dev/sdb bs=1M oflag=sync
/bin/echo -e "d\n2\nn\np\n2\n143360\n\nw\n" | fdisk /dev/sdb
mkfs.ext4 -O ^has_journal -b 4096 -L rootfs  /dev/sdb2
mount /dev/sdb2 rootfs/
cp -ar centos7-rootfs/\* rootfs/
/bin/cat >> rootfs/etc/rc.d/rc.local <<FOE
echo '123456' | passwd root --stdin
[ ! -d /root/.ssh ] && mkdir -p /root/.ssh && touch /root/.ssh/authorized_keys && chmod 700 /root/.ssh
FOE
chmod +x rootfs/etc/rc.d/rc.local
/bin/cat >> rootfs/usr/lib/systemd/system/rc-local.service <<FOE

[Install]
WantedBy=multi-user.target
FOE
cd rootfs/
ln -s usr/lib/systemd/system/rc-local.service etc/systemd/system/multi-user.target.wants/rc-local.service
cd -
sed -i "s/#PermitRootLogin yes/PermitRootLogin yes/g" rootfs/etc/ssh/sshd_config
/bin/cat > rootfs/etc/fstab <<FOE

# <file system> <dir>   <type>  <options>                       <dump>  <pass>

/dev/mmcblk0p1  /boot   vfat    defaults                        0               2
/dev/mmcblk0p2  /       ext4    defaults,noatime                0               1
FOE
umount rootfs/
sync

So now I am running CentOS 7.2 aarch edition on my pine64+ with hdmi output.
