### ISSUE TITLE
image expansion on 1st boot

### ISSUE THREAD

**Issue by ThomasKaiser** [longsleep/build-pine64-image#2]
Not a real 'issue' but more an request for enhancements (can be closed immediately if you don't care). 

Armbian uses a 'service' that gets called automagically at the 1st boot and decides to resize the rootfs to the maximum size if ext4 has been chosen. And that is tested by a few thousand users/installations in the meantime: https://github.com/igorpecovnik/lib/blob/master/scripts/firstrun

You could use this also and provide smaller images. Tested with your Xenial image. You just need to delete everything that's Armbian specific. BTW: using 3.10.65 kernel some thermal/performance stuff can be read out through sysfs. I created a template for RPi-Monitor to get a clue how A64 behaves already (just to get an idea [when you're running in overheating problems](http://forum.armbian.com/index.php/topic/751-rfc-support-cortex-a53arm64/?p=5731) or maybe undervoltage)

**Comment by longsleep** [comment]
Yeah, i certainly can add that - though frankly i did not want to make it too easy for "end users" for now (because they are crap images). 

Also, i would prefer to have the resizing code in initrd to actually run it before rootfs is mounted (like done in Ubuntu Snappy).

I did not know about the RPi monitor - seems very useful!

**Comment by ThomasKaiser** [comment]
Thx for mentioning the way Snappy does fs resizing, I will have a look.

This RPi-Monitor stuff is really useful especially when dvfs/throttling should be considered (with 3.10.65 and without heatsink already pretty funny). With Xenial it's basically walking through the [InstallRPiMonitor function in install-rpi-monitor-for-h3.sh](http://kaiser-edv.de/tmp/4U4tkD/) and replacing cpu.conf and temperature.conf with [Allwinner_A64.conf](http://pastebin.com/bSTYCQ5u). With Arch Linux it was more PITA (wrong/missing architecture in AUR package, even cpan needed to get all perl modules, wrong memory read out)
