### ISSUE TITLE
Thermal anomalies w.r.t. Linux sysfs interface

### ISSUE THREAD

**Issue by texadactyl** [longsleep/build-pine64-image#21]
This is not a show-stopper!!  I do appreciate all the effort you have given.
1. /sys/class/thermal/thermal_zone0/temp :: The units appear to be in degrees Celsius.  However, the Linux standard sysfs interface requires the units to be in millidegrees Celsius e.g. what appears as 65 should appear as 65000.
2. /sys/class/hwmon :: has a subdirectory with a nonstandard name i.e. "mbus_pmu".  I was expecting something of the form "hwmon*'.
3.  /sys/class/hwmon should have an additional hwmon\* subdirectory to correspond to /sys/class/thermal/thermal_zone0.  Then, the standard Linux tools (E.g. mate-sensors, psensor, & lm-sensors) would be able to provide a display on panel 0 of the various desktops.

Thank you again,

Richard

**Comment by longsleep** [comment]
Yes that is how it is with the BSP Kernel. There are plenty of things non standard. Using mainline is the solution.
