### ISSUE TITLE
How to get distribution into second partition

### ISSUE THREAD

**Issue by pine64-android** [longsleep/build-pine64-image#31]
There are no instructions for how to get the distribution into the second partition. Could you please add something to help inexperienced people past this point?

**Comment by pine64-android** [comment]
I think I see what the problem is, the changes made to make_kernel_tarball.sh for uEnv.txt also need to be done in make_rootfs.sh. Without these parallel uEnv changes the rootfs install errors out when run with  make_simpleimage.sh

**Comment by pine64-android** [comment]
I'm unable to figure out how to build an image with a distro user space. I can get close but all of the bits are not quite all in the right places.  I need help with some guidance on the right order to do everything with scripts.

I got to a point when all of the scripts would run without error, but uboot doesn't have the right partition mounted and therefore it can't find the kernel. So I am probably doing something in the wrong order.

**Comment by longsleep** [comment]
These scripts are for experienced software developers. You need to be able to figure this out yourself as i lack the time to explain or provide more than just the very basic help by pointing to things.
