### ISSUE TITLE
make arch/arm64/configs/sun50iw1p1smp_linux_defconfig fails

### ISSUE THREAD

**Issue by vpodzime** [longsleep/build-pine64-image#34]
I'm getting the following failure when I try to run `make arch/arm64/configs/sun50iw1p1smp_linux_defconfig` on my PINE64:

```
drivers/net/wireless/bcmdhd/Kconfig:50:warning: defaults for choice values not supported
***
*** Can't find default configuration "arch/arm64/configs/arch/arm64/configs/sun50iw1p1smp_linux_defconfig"!
***
```

Sorry if this is an entirely stupid report, I'm nowhere near to be a skilled kernel "compiler".

**Comment by vpodzime** [comment]
Forgot to mention that the above is from the _pine64-hacks-1.2_ branch.

**Comment by longsleep** [comment]
Something is wrong with your setup (path arch/arm64/configs is duplicated) from the error message above. Check the instructions in the kernel folder for command line examples which work.
