### ISSUE TITLE
installing mate fails

### ISSUE THREAD

**Issue by My1** [longsleep/build-pine64-image#41]
the pine says that ubuntu-mate-desktop and ubuntu-mate-core cant be installed because it depends on gtk2-engines-pixbuf which also cannot be installed because that depends on libgtk2.0-0 (=2.24.30-1ubuntu1) but 2.24.30-1ubuntu1-16.04.1 is installed.

an Idea of how to get this working?

**Comment by longsleep** [comment]
Wait until the Ubuntu repository is fixed. My image have the https://help.ubuntu.com/community/UbuntuBackports repository enabled which sometimes has incomplete dependency chains.

**Comment by My1** [comment]
okay, but weird from first glance it looks like it's the same version (2.24.30) but the other one has some more text to it, and the version comparison looks quite strict.

**Comment by My1** [comment]
but do you have some Idea when they resolve their backports problems?

**Comment by longsleep** [comment]
No idea. I rolled a new image, starting from 20161218-1 it is no longer using backports and proposed repositories. This gives stable dependencies and mate installs just fine on that image. Unfortunately there is no way going back. So to get this, best to use the new image and start from scratch.

**Comment by My1** [comment]
stupid question: where do I find it? releases are blank.

**Comment by longsleep** [comment]
Err, https://www.stdin.xyz/downloads/people/longsleep/pine64-images/ubuntu/ - release overview at http://forum.pine64.org/showthread.php?tid=376

**Comment by My1** [comment]
thanks.
