### ISSUE TITLE
mbr structures cannot be larger than 446 bytes (when building snappy image)

### ISSUE THREAD

**Issue by tyuiasdf** [longsleep/build-pine64-image#43]
Hi!

I tried run the "UBUNTU_IMAGE_SKIP_COPY_UNVERIFIED_MODEL=1 /snap/bin/ubuntu-image -c beta --image-size 2G --extra-snaps pine64_16.04-1_arm64.snap --extra-snaps kernel/pine64-kernel_3.10.104-1_arm64.snap -o test1.img pine64.model --debug" to build the image but encounter error as shown:

ERROR:ubuntu-image:uncaught exception in state machine step: [2] load_gadget_yaml
Traceback (most recent call last):
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/state.py", line 73, in __next__
    step()
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/builder.py", line 133, in load_gadget_yaml
    self.gadget = parse_yaml(fp)
  File "/snap/ubuntu-image/44/lib/python3.5/site-packages/ubuntu_image/parser.py", line 413, in parse
    'mbr structures cannot be larger than 446 bytes.')
ubuntu_image.parser.GadgetSpecificationError: mbr structures cannot be larger than 446 bytes.
ERROR:ubuntu-image:gadget.yaml parse error

Is it because of the values in gadget.yaml? Thank you!

**Comment by longsleep** [comment]
Snappy stuff is still wip, but the error you get does not happen for me. The gadget and kernel snaps should work fine as commited. Please check that you have the latest versions of snapcraft and ubuntu-image. I will continue on this the next couple of days.

**Comment by tyuiasdf** [comment]
The versions of snapcraft and ubuntu-image i used are 2.24 and 0.13+17.04ubuntu1 respectively in Ubuntu 16.04.1 LTS. And have try using ubuntu-image 0.12+16.04ubuntu1 too, but still encounter same error.

**Comment by longsleep** [comment]
Mhm i currently use
```
ubuntu-image  0.10+real1  25   canonical  devmode
```

**Comment by longsleep** [comment]
Ok, i see - my version does not have this check and my current gadget yaml is not compliant to https://github.com/CanonicalLtd/ubuntu-image/blob/master/ubuntu_image/parser.py#L417 - i need to think about this. How and why do you use newer ubuntu-image snap? Store yields only 0.10 for me.

**Comment by tyuiasdf** [comment]
Appreciate it and Thank you very much! :)

**Comment by tyuiasdf** [comment]
So the generated image will boot until "Press enter to configure." which is displayed on serial console. Right?

**Comment by longsleep** [comment]
Yes. Then another issue appears (also the reason why i did not release anything yet). https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1652262

**Comment by tyuiasdf** [comment]
Ok. Thanks a lot for the information!
