### ISSUE TITLE
Add custom setup script

### ISSUE THREAD

**Issue by ThomDietrich** [longsleep/build-pine64-image#48]
Hey @longsleep,
as you probably already guessed, I'm currently working on a project based on yours. Besides building the image, I'm injecting a custom `rc.local`, calling `/boot/first-boot.sh`, in order to do some first boot modifications.

At the moment this is simply done by appending commands to the bottom of `simpleimage/make_rootfs.sh`. Would you be interested in a PR for these preparations?

**Comment by longsleep** [comment]
Hey Thomas,

On Mon, Feb 13, 2017 at 5:11 PM, Thomas Dietrich <notifications@github.com>
wrote:

> Hey @longsleep <https://github.com/longsleep>,
> as you probably already guessed, I'm currently working on a project based
> on yours. Besides building the image, I'm injecting a custom rc.local,
> calling /boot/first-boot.sh, in order to do some first boot modifications.
>
> At the moment this is simply done by appending commands to the bottom of
> simpleimage/make_rootfs.sh. Would you be interested in a PR for these
> preparations?
>

Sure, i would prefer some `run-parts` based hook approach though, which
simply runs additional scripts at the various stages based on a simple file
naming scheme similar to what pbuilder is doing with the --hookdir
parameter. See
http://manpages.ubuntu.com/manpages/precise/man8/pbuilder.8.html for
inspiriation.

Cheers
Simon

**Comment by ThomDietrich** [comment]
You know, looking at this with fresh eyes, that **is** the better solution 👍 I've started to do small modifications in rc.local once and never thought twice about that since. I'd leave `/boot/whatevername.sh` where it is, allows modifications or settings to be applied after flashing.
I'll come back here soon.

**Comment by longsleep** [comment]
Closing for now, please open a PR if you have something and/or still relevant.

**Comment by ThomDietrich** [comment]
I didn't look into it any further as my (inferior) solution is doing the job just fine. I'll open a PR if I ever get around changing it. Thanks for the reminder. Best!
