### ISSUE TITLE
Preparing kernel for NFS/FEL-Boot?

### ISSUE THREAD

**Issue by ThomasKaiser** [longsleep/build-pine64-image#6]
Not an issue more a suggestion/question. Since A64 can [boot through USB](http://linux-sunxi.org/FEL/USBBoot) it might be worth an idea to prepare the kernel to load the rootfs through NFS.

Since we (Armbian Team) support [quite a few sunxi boards](http://www.armbian.com/download/) we had a discussion whether we could use both FEL-boot and NFS to reduce the time between build and boot to 0 seconds (possible). The board will be connected to the build host via USB using the upper OTG port, after image creation the rootfs will be provided by NFS and by calling _sunxi-fel_ the Pine64 already boots without inserted SD card. This might speed up OS image testing (not that important at this stage) but also situations where the board might frequently crash to prevent SD card corruption.

Link to [discussion](https://github.com/igorpecovnik/lib/issues/198) and [ kernel config / Armbian build system changes](https://github.com/zador-blood-stained/lib/commit/df1b8857e5708a61ceb2717626b99f1bece17be3)

**Comment by longsleep** [comment]
Sure i will add the NFS stuff to the Kernel config. Though i will probably not get myself too deep into FEL-anything :)

**Comment by ThomasKaiser** [comment]
Ask apritzel, he loves _sunxi-fel_ in the meantime ;)

Changing kernel settings already should be sufficient since everything else is stuff for uEnv.txt (the BSP u-boot seems recent enough. At least that's my hope)

**Comment by longsleep** [comment]
Can you use the stuff from initrd? After thinking about it, i would rather not add all the NFS stuff directly into the Kernel by default as most users will never need it. Maybe you can add them to initrd?

**Comment by longsleep** [comment]
Ok, everything should have been enabled in https://github.com/longsleep/linux-pine64/commit/decaa59a513a9d8584b279ab8c03aa5f6b358202
