### ISSUE TITLE
Can't pass kernel arguments using extraargs in uEnv.txt

### ISSUE THREAD

**Issue by alexmat** [longsleep/build-pine64-image#62]
Here is what my /boot/uEnv.txt looks like on my Pine64:

extraargs=root=/dev/mmcblk0p2 ipv6.disable=1
kernel_filename=pine64/Image
initrd_filename=initrd.img

However the kernel is not honoring the ipv6.disable flag.

Looking at dmesg, I see this line confirming that the ipv6.disable flag was not passed: 

[    0.000000] Kernel command line: console=ttyS0,115200 earlycon=uart,mmio32,0x01c28000 mac_addr=fe:7c:d1:84:c5:7a root=/dev/mmcblk0p2 ro rootwait

I flashed the simple image and am using my own rootfs.

**Comment by longsleep** [comment]
BSP U-Boot as in my releases does not support `exstaargs`. Instead use `optargs`. See https://github.com/longsleep/u-boot-pine64/blob/pine64-hacks/include/configs/sun50iw1p1.h#L382 for reference.
