### ISSUE TITLE
Error installing on Armbian 5.27 for Sopine

### ISSUE THREAD

**Issue by stf144** [longsleep/build-pine64-image#65]
When I tried to install on Armbian 5.27 for the Sopine, the script crashed with this error:
./install_desktop.sh: line119: /etc/chromium-browser/default: no such file or directory

**Comment by pfeerick** [comment]
IMO, unless this affects longsleeps build, it's not his problem, but it's an easy enough fix, so if he's happy with my change, it's resolved by the PR I just made.
