### ISSUE TITLE
Linux kernel tarball: Include Linux kernel headers and firmware as well

### ISSUE THREAD

**Issue by umiddelb** [longsleep/build-pine64-image#7]
Hi Simon,

you may add the Linux kernel headers and firmware as well, like described [here](https://github.com/umiddelb/aarch64/wiki/Build-Linux-3.10-BSP-kernel-for-PINE64).

Cheers
Uli

**Comment by longsleep** [comment]
Hi Uli, good point. Will do so.

**Comment by longsleep** [comment]
Done
