### ISSUE TITLE
Orange Pi Win get stuck at Enter new UNIX password when ssh first boot

### ISSUE THREAD

**Issue by k1ngH0st** [longsleep/build-pine64-image#70]
Well, the title is self explanatory. I am trying the new stable release for the Orange PI win from armbian (thank you guys!) but when booting for the first time in headless mode via SSH through Ethernet cable it gets stuck at "Enter new UNIX password". I put the new password and nothing happens. If I unplug the cable to force the SSH server to close the connection and then I plug it back again, the password is kept the old one (default 1234) and the problem repeats.
Is there someone with the same issue?
Thanks in advance!

**Comment by k1ngH0st** [comment]
After some tests I finally got to change the password, but it gets stuck after, or even before sometimes if I reboot. It seems that the SSH tunnel is simply not stable. I should mention that the configuration of OS and dhcp server I use to work in headless mode is exactly the same I have used with old (unstable) releases, and as for the SSH connection it worked perfectly.

**Comment by pfeerick** [comment]
Er? Why are you posting this against the pine64 linux build project github? If it's related to the Armbian project, maybe you should be posting over on their forum, [under the Allwinner A64 topic](https://forum.armbian.com/forum/18-allwinner-a64-h5/)?

**Comment by longsleep** [comment]
Closing since unrelated to Pine64.
