### ISSUE TITLE
No eMMC memory detected

### ISSUE THREAD

**Issue by JackCarterSmith** [longsleep/build-pine64-image#71]
No eMMC memory detected. Is there a specific compilation to do or is it a driver problem ? (The support of the pine64 informed me that it was possible that the driver of my chip eMMC is 5.0)

**Comment by pfeerick** [comment]
I think there was a problem with eMMC 5 (64GB -> Sandisk?) If so, you will want one of the ayufan-pine64 builds over at https://github.com/ayufan-pine64/linux-build/releases, and probably a version later than 0.7.18. I'm using the latest 0.7.19 on a pinebook with a 64GB Sandisk eMMC, and it is working fine.

**Comment by JackCarterSmith** [comment]
32GB probably Sandisk eMMC, I'll try what you tell me if it works, I use a Pine64 LTS (SoPine).

**Comment by longsleep** [comment]
Not sure how this issue is related to this project. For support please visit Pine64 forums - this is a bug tracker for software bugs.
