### ISSUE TITLE
FATAL ERROR OF GCC.5 WHILE BUILDING UBOOT

### ISSUE THREAD

**Issue by sravanianattala** [longsleep/build-pine64-image#72]
Hi, i am sravani.
i am doing uboot building on ubuntu 16.04.when i was ran the command ''make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-'' it shows me fatal error of gcc i.e fatal error: linux/compiler-gcc5.h: No such file or directory
and the compilation terminated
anything wrong with compiler? or else?
please tell me the solution?i have to submit my post graduation project.
@sravanianattala

**Comment by sravanianattala** [comment]
Hi, i am sravani.
i am doing uboot building on ubuntu 16.04.when i was ran the command ''make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-'' it shows me fatal error of gcc i.e fatal error: linux/compiler-gcc5.h: No such file or directory
and the compilation terminated
anything wrong with compiler? or else?
please tell me the solution?i have to submit my post graduation project.
@sravanianattala

**Comment by sravanianattala** [comment]
![screenshot from 2018-07-10 12-19-12](https://user-images.githubusercontent.com/41044077/42494160-102c65d0-843d-11e8-9b6d-d19fea12659c.png)

**Comment by longsleep** [comment]
This error seems to be unrelated to this project - please only open issues for building pine64 u-boot from my tree here.

**Comment by sravanianattala** [comment]
OK, thank you
