### ISSUE TITLE
Makefile:1200: *** missing separator

### ISSUE THREAD

**Issue by nickbetteridge** [longsleep/build-pine64-image#8]
Just tried to do a build:

```
# arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Ubuntu/Linaro 4.8.5-1ubuntu1) 4.8.5
# git clone --depth 1 --branch pine64-hacks --single-branch https://github.com/longsleep/u-boot-pine64.git u-boot-pine64
# make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- sun50iw1p1_config
# make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
Makefile:1200: *** missing separator (did you mean TAB instead of 8 spaces?). Stop.
```

Looking at the top Makefile, line 1200 has `-R --c++-kinds=+p --fields=+iaS --extra=+q` - I'm no make expert, so I'm not too sure how to fix this - any suggestions?

Thanks
NIck

**Comment by longsleep** [comment]
Mhm that line looks wrong indeed. Easy suggestion - try to remove it :) What make are you using - my GNU Make 3.81 does not seem to care.

**Comment by nickbetteridge** [comment]
Using GNU make 4.0.

Just appended the offending line to the previous line and the beauty worked :) - now moving on to build the rest of the image - thanks for doing all of this work to build images.

**Comment by longsleep** [comment]
Fixed in makefile.
