### ISSUE TITLE
Static linking against glibc, can't use --gc-sections

### ISSUE THREAD

**Issue by whongx** [longsleep/build-pine64-image#9]
Hi, this came out when try to configure and build busybox (make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j4):

   AR      networking/lib.a
   LINK    busybox_unstripped
Static linking against glibc, can't use --gc-sections
Trying libraries: crypt m
  Library crypt is not needed, excluding it
  Library m is needed, can't exclude it (yet)
Final link with: m

Is this an error? And i don't know whether it is compiled successfully or not?

Thanks!
wong

**Comment by longsleep** [comment]
No, this is no error. You know if it worked when there is a "busybox" binary file in the base folder of your busybox tree.

```
file ./busybox
./busybox: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, for GNU/Linux 3.7.0, BuildID[sha1]=a4d0ad6f7fa0e7143911132732f1e23bb3fbba69, stripped
```
